language: ruby
rvm:
- 2.1.0
install:
- sudo FORCE_ADD_APT_REPOSITORY=1 add-apt-repository ppa:pharo/stable
- sudo apt-get update
- sudo apt-get install pharo-launcher:i386
- gem install kramdown
- gem install jekyll
- sudo chmod +x _pillar/downloadVM.sh
- cd _pillar ; ./downloadVM.sh
script: jekyll build
after_success:
- if [[ ! -d ~/.ssh ]]; then mkdir ~/.ssh; fi
- if [[ ! -f ~/.ssh/config ]]; then touch ~/.ssh/config; fi
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- cat ~/.ssh/config
- git clone https://BenjaminVanRyseghem:${GH_TOKEN}@github.com/SpecForPharo/SpecForPharo.github.io.git ../jekyll
- rm -rf ../jekyll/*
- cp -r _site/* ../jekyll/
- cd ../jekyll
- ls
- git config user.email "${GIT_EMAIL}"
- git config user.name "${GIT_NAME}"
- git status
- git add --all *
- git commit -am "Generation of the Jekyll website"
- git push https://BenjaminVanRyseghem:${GH_TOKEN}@github.com/SpecForPharo/SpecForPharo.github.io.git master
env:
  global:
  - secure: Ple/yWUxwngx2qAetIUDfcUAaHZ0kURU1tmb1X88YLbgLwTKiPFbbd0ScHOSvgqoG61T9cBAOuu+HAN/RsI0r1X76hysoYGaQW8uSDPt4Mf9XYrJJcQov6hXPSQZ2LoTxSkMprEXTI2CbfPQYgYgY/5ybfw6Mbr7uaT1rML9YDI=
  - secure: ifRVpDsSCHBTDJxlz7cQQHikumTPa6f5rRyJFBdFiqbQU0frv8GBsjNwptX+s1nTFAsihGF9TKhJvXfTIsf/Zpx+qS/ZLzdVNZzVfVGYb0foX+te0AFmOulNHo3VpanhYXw9r9WtDAUbJ7WKCE+xp8MAJYtiRNWtQTCQIajSxlY=
  - secure: GEmThaaJB5WSfnlQwsca+sLpZHIXRW9AWw+BmlSD6evi8GEa3TG6OfHvGKg4QqsSrkcFL4WJj1qI11HMC8Aj22VDsCorzKKP5sHraDZSsrKyWR2AKyLOwJC2D2ifqWtJ6J1esJ9D/9fmf0DdhuC9u6/+kny5iKHbztsFKw/lkhE=
